"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import errorresponse as shared_errorresponse
from ..shared import secret as shared_secret
from typing import Optional


@dataclasses.dataclass
class RollbackSnapshotsRequest:
    
    request_body: int = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""Rollback workspace secret snapshots"""  
    workspace_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'workspaceId', 'style': 'simple', 'explode': False }})
    r"""Workspace ID"""  
    

@dataclasses.dataclass
class RollbackSnapshotsResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    error_response: Optional[shared_errorresponse.ErrorResponse] = dataclasses.field(default=None)
    r"""Unauthorized"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    secrets: Optional[list[shared_secret.Secret]] = dataclasses.field(default=None)
    r"""OK"""  
    