"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from . import utils
from infisical.models import operations, shared
from typing import Any, Optional

class Workspaces:
    r"""Everything about workspaces"""
    _client: requests_http.Session
    _security_client: requests_http.Session
    _server_url: str
    _language: str
    _sdk_version: str
    _gen_version: str

    def __init__(self, client: requests_http.Session, security_client: requests_http.Session, server_url: str, language: str, sdk_version: str, gen_version: str) -> None:
        self._client = client
        self._security_client = security_client
        self._server_url = server_url
        self._language = language
        self._sdk_version = sdk_version
        self._gen_version = gen_version
        
    def delete_membership(self, request: operations.DeleteWorkspaceMembershipRequest) -> operations.DeleteWorkspaceMembershipResponse:
        r"""Delete workspace membership
        Delete workspace membership
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.DeleteWorkspaceMembershipRequest, base_url, '/workspace/{workspaceId}/memberships/{membershipId}', request)
        
        
        client = self._security_client
        
        http_res = client.request('DELETE', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.DeleteWorkspaceMembershipResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.Membership])
                res.membership = out
        elif http_res.status_code in [401, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ErrorResponse])
                res.error_response = out

        return res

    def list_keys(self, request: operations.ListKeysRequest) -> operations.ListKeysResponse:
        r"""Get workspace encrypted key
        Get workspace encrypted key
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.ListKeysRequest, base_url, '/workspace/{workspaceId}/encrypted-key', request)
        
        
        client = self._security_client
        
        http_res = client.request('GET', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ListKeysResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[list[shared.Key]])
                res.keys = out
        elif http_res.status_code in [401, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ErrorResponse])
                res.error_response = out

        return res

    def list_logs(self, request: operations.ListLogsRequest) -> operations.ListLogsResponse:
        r"""Get workspace logs
        Get workspace logs
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.ListLogsRequest, base_url, '/workspace/{workspaceId}/logs', request)
        
        
        client = self._security_client
        
        http_res = client.request('GET', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ListLogsResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[list[shared.Log]])
                res.logs = out
        elif http_res.status_code in [401, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ErrorResponse])
                res.error_response = out

        return res

    def list_membership(self, request: operations.ListWorkspaceMembershipsRequest) -> operations.ListWorkspaceMembershipsResponse:
        r"""Get workspace memberships
        Get workspace memberships
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.ListWorkspaceMembershipsRequest, base_url, '/workspace/{workspaceId}/memberships', request)
        
        
        client = self._security_client
        
        http_res = client.request('GET', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ListWorkspaceMembershipsResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[list[shared.Membership]])
                res.memberships = out
        elif http_res.status_code in [401, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ErrorResponse])
                res.error_response = out

        return res

    def list_snapshots(self, request: operations.ListSnapshotsRequest) -> operations.ListSnapshotsResponse:
        r"""List workspace snapshots
        List workspace snapshots
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.ListSnapshotsRequest, base_url, '/workspace/{workspaceId}/snapshots', request)
        
        
        client = self._security_client
        
        http_res = client.request('GET', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ListSnapshotsResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[list[Any]])
                res.snapshots = out
        elif http_res.status_code in [401, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ErrorResponse])
                res.error_response = out

        return res

    def list_workspace(self, request: operations.ListWorkspaceRequest) -> operations.ListWorkspaceResponse:
        r"""List organization workspaces
        List organization workspaces
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.ListWorkspaceRequest, base_url, '/organizations/{organizationId}/workspaces', request)
        
        
        client = self._security_client
        
        http_res = client.request('GET', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ListWorkspaceResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[list[shared.Workspace]])
                res.workspaces = out
        elif http_res.status_code in [401, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ErrorResponse])
                res.error_response = out

        return res

    def rollback_snapshots(self, request: operations.RollbackSnapshotsRequest) -> operations.RollbackSnapshotsResponse:
        r"""Rollback workspace secret snapshots
        Rollback workspace secret snapshots
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.RollbackSnapshotsRequest, base_url, '/workspace/{workspaceId}/secret-snapshots/rollback', request)
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "request_body", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = self._security_client
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.RollbackSnapshotsResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[list[shared.Secret]])
                res.secrets = out
        elif http_res.status_code in [401, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ErrorResponse])
                res.error_response = out

        return res

    def update_membership(self, request: operations.UpdateWorkspaceMembershipRequest) -> operations.UpdateWorkspaceMembershipResponse:
        r"""Update workspace membership
        Update workspace membership
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.UpdateWorkspaceMembershipRequest, base_url, '/workspace/{workspaceId}/memberships/{membershipId}', request)
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "membership", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = self._security_client
        
        http_res = client.request('PATCH', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.UpdateWorkspaceMembershipResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.Membership])
                res.membership = out
        elif http_res.status_code in [401, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ErrorResponse])
                res.error_response = out

        return res

    